name: samokat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  toggle_switch: ^2.3.0

dev_dependencies: 
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

